//var SERVER_HOST = "http://172.20.100.142:8080/TASServer/"
//var SERVER_HOST_TEST = "http://192.168.10.102:8080/TASServer/"

//var SERVER_HOST_FORMAL = "http://172.20.100.142:8080/TASServer/"
//var SERVER_HOST_FORMAL="http://kq.qdairport.com:9099/TASServer/"
var SERVER_HOST_FORMAL = "http://192.168.3.69:8080/TASServer/"
//var SERVER_HOST_FORMAL = "http://192.168.3.174:8080/BizApp/"

var MODULE_TEST="test/test";
var MODULE_DAILY="control/daily";
var MODULE_DETAIL="control/detail";
var MODULE_PINFOREC="control/p_info_rec";
var MODULE_LOGIN="control/login";
var MODULE_DEPT="control/dept";
var MODULE_DEPTLIST="control/deptlist";
var MODULE_DEPTRECORD="control/deptrecord";
var MODULE_SWORKLOG="control/insertlog"
var MODULE_QTWORKLOG="control/querytoplog"
var MODULE_QDWORKLOG="control/querydatelog"
var MODULE_INTEREST="control/interest"
var MODULE_INTEREST_LIST="control/interestlist"
var MODULE_INTEREST_LISTBYID="control/interestlistbyid"
var MODULE_FUZZYQUERY_EMPLOYEE="control/fuzzyqueryemployee"
var MODULE_UPDATE_INTEREST="control/updateinterest"
var MODULE_TODAY_OVERVIEW="control/todayoverview"
var MODULE_SIGN="control/sign"
var MODULE_OUTSIGN="control/outsign" 
var MODULE_QUOTA="control/quota"
var MODULE_ALLEMPLOYEE="control/allemployee"
var MODULE_CONTACT="control/contact"
var MODULE_MODIFYPWD="control/modifypwd"
var MODULE_BELONG_GROUP="control/belonggroupquery"
var MODULE_GROUP_MEMBER="control/groupmemberquery"
var MODULE_ALLDEPT_RECORD="control/alldeptrecord"
var MODULE_FULL_DEPT_RECORD="control/fulldeptrecord"
var MODULE_ON_OFF_RECORD="control/onoffdutyrcd"
var MODULE_ADD_RECORD_REMARK="control/addrecordremark"
var MODULE_GET_RECORD_REMARK="control/getrecordremark"
var MODULE_UPDATE_RECORD_REMARK="control/updaterecordremark"
var MODULE_SDAYS_RECORD_REMARK="control/get7daysrecordremark"
var MODULE_CHECK_HAS_RECORD="control/checkhasattendance"
var MODULE_UNCHECK_PERSON="control/uncheckperson"
var MODULE_CHECK_DEPT_AUTHORITY="control/deptauthority"
var MODULE_CHECK_MOBILE_VERSION="control/mobileversion"
var MODULE_LATER_CHECK_PERSON="control/latercheckperson"
var MODULE_OUT_CHECK_PERSON="control/outcheckperson"
var MODULE_DLEXCEL_PERSON="control/personexcel"
var MODULE_DLEXCEL_DEPT="control/deptexcel"
var MODULE_INSPECT="control/inspect"
var MODULE_INSPECT_HISTORY="control/inspecthistory"

